# Site settings
title: Claire Gaulin Brown Artworks
email: gaulinbrown@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A website for Claire Gaulin Brown, professional artist and illustrator from Vancouver Island, Canada.
baseurl:  # the subpath of your site, e.g. /blog/
url:   # the base hostname & protocol for your site
twitter_username: twitter_username
github_username:  github_username

# Build settings
markdown: kramdown

highlighter: pygments

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: false
    permalink: /poetry/:path/
  services:
    output: true
    permalink: /services/:path/
